/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/services/v1/stations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Gets the metadata for one or more stations
     * @description Retrieves the station metadata for one or more stations
     */
    get: operations['getStations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/v1/reference-data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Gets reference data
     * @description Retrieves one or more types of reference data
     */
    get: operations['getReferenceData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/v1/forecasts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Gets forecast data for one or more stations
     * @description Retrieves forecast data for one or more stations
     */
    get: operations['getForecasts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/v1/data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Gets data for one or more stations
     * @description Retrieves data for one or more stations
     */
    get: operations['getData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Data for a given station and element */
    DataDTO: {
      stationElement?: components['schemas']['StationElementDTO'];
      timingCentralTendencies?: components['schemas']['TimingCentralTendenciesDTO'];
      values?: components['schemas']['DataValueDTO'][];
      /** @example Unsupported operation - the insertOrUpdateBeginDate parameter is not supported for derived data (NOTE: Only included when there is an error). */
      error?: string;
    };
    /** @description A data value */
    DataValueDTO: {
      /**
       * @description The timestamp of the data. Used only for DAILY and HOURLY durations.
       * @example 2022-01-01
       */
      date?: string;
      /**
       * Format: int32
       * @description The month of the data value (1-12). Used only for MONTHLY and SEMIMONTHLY durations.
       * @example 1
       */
      month?: number;
      /**
       * @description The half of month of the data value ('1' for first half, '2' for second half). Used only for SEMIMONTHLY durations.
       * @example 1
       */
      monthPart?: string;
      /**
       * Format: int32
       * @description The year of the data value. Used only for WATER_YEAR, CALENDAR_YEAR, MONTHLY, and SEMIMONTHLY durations.
       * @example 2022
       */
      year?: number;
      /**
       * @description The date the data value was collected. Used only for SEMIMONTHLY durations.
       * @example 2021-12-31
       */
      collectionDate?: string;
      /**
       * @description The data value
       * @example 1.2
       */
      value?: number;
      /**
       * @description The qc flag of the data value
       * @example E
       */
      qcFlag?: string;
      /**
       * @description The qa flag of the data value
       * @example A
       */
      qaFlag?: string;
      /**
       * @description The original data value
       * @example 1.3
       */
      origValue?: number;
      /**
       * @description The original qc flag of the data value
       * @example V
       */
      origQcFlag?: string;
      /**
       * @description The 30-year average
       * @example 1.4
       */
      average?: number;
      /**
       * @description The 30-year median
       * @example 1
       */
      median?: number;
    };
    /** @description Contains DCO reference data. */
    DcoDTO: {
      /**
       * @description The DCO code
       * @example OR
       */
      code?: string;
      /**
       * @description The DCO Name
       * @example OREGON
       */
      name?: string;
    };
    /** @description Contains duration reference data. */
    DurationDTO: {
      /**
       * @description The duration code
       * @example D
       */
      code?: string;
      /**
       * @description The duration name
       * @example DAILY
       */
      name?: string;
      /**
       * @description The duration in minutes
       * @example 1440
       */
      durationMinutes?: string;
    };
    /** @description Contains element reference data. */
    ElementDTO: {
      /**
       * @description The element code
       * @example PREC
       */
      code?: string;
      /**
       * @description The element name
       * @example PRECIPITATION ACCUMULATION
       */
      name?: string;
      /**
       * @description The physical element name
       * @example precipitation accumulation
       */
      physicalElementName?: string;
      /**
       * @description The function code
       * @example C
       */
      functionCode?: string;
      /**
       * Format: int32
       * @description The precision of the data
       * @example 2
       */
      dataPrecision?: number;
      /**
       * @description The element description
       * @example Water Year Accumulated Precipitation
       */
      description?: string;
      /**
       * @description The stored unit code
       * @example in
       */
      storedUnitCode?: string;
      /**
       * @description The english unit code
       * @example in
       */
      englishUnitCode?: string;
      /**
       * @description The metric unit code
       * @example mm
       */
      metricUnitCode?: string;
    };
    /** @description Contains one or more forecasts for a forecast point. */
    ForecastDTO: {
      /**
       * @description The station triplet of the forecast point.
       * @example 09430500:CO:USGS
       */
      stationTriplet?: string;
      /**
       * @description The name of the forecast point.
       * @example Gila R at Gila
       */
      forecastPointName?: string;
      /** @description Contains forecast data for a forecast point. */
      data?: components['schemas']['ForecastDataDTO'][];
    };
    /** @description Contains forecast data for a forecast point. */
    ForecastDataDTO: {
      /**
       * @description The element code related to the forecast record.
       * @example SRVO
       */
      elementCode?: string;
      /**
       * @description The start (MM-DD) and end (MM-DD) of the forecast period that the forecast is for.
       * @example [
       *       "04-01",
       *       "07-31"
       *     ]
       */
      forecastPeriod?: string[];
      /**
       * @description Indicates the status of the Forecast.
       * @example final
       */
      forecastStatus?: string;
      /**
       * @description The issue date of the forecast.
       * @example 2023-10-02 07:45:52
       */
      issueDate?: string;
      /**
       * @description The forecast period normal.
       * @example 13.6
       */
      periodNormal?: number;
      /**
       * @description The publication date of the forecast value.
       * @example 2023-04-01
       */
      publicationDate?: string;
      /**
       * @description The unit code of a forecast.
       * @example kac_ft
       */
      unitCode?: string;
      /**
       * @description A dictionary of forecast values where the key is the exceedence probability and the value is the corresponding forecast value.
       * @example {
       *       "10": 36.5,
       *       "30": 28.3,
       *       "50": 24.1
       *     }
       */
      forecastValues?: {
        [key: string]: number;
      };
    };
    /** @description Contains forecast period reference data. */
    ForecastPeriodDTO: {
      /**
       * @description The forecast period code
       * @example D1
       */
      code?: string;
      /**
       * @description The forecast period name
       * @example J15-JAN
       */
      name?: string;
      /**
       * @description The forecast period description
       * @example Jan 15 through Jan
       */
      description?: string;
      /**
       * @description The beginning month and day for the forecast period
       * @example 01-15
       */
      beginMonthDay?: string;
      /**
       * @description The ending month and day for the forecast period
       * @example 01-31
       */
      endMonthDay?: string;
    };
    /** @description Contains information about a forecast point */
    ForecastPointDTO: {
      /**
       * @description The name of the forecast point
       * @example Alamosa Ck ab Terrace Reservoir
       */
      name?: string;
      /**
       * @description The user name of the forecaster who forecasts for this station
       * @example agoodbody
       */
      forecaster?: string;
      /**
       * @description The name to display in the UI for the profile type
       * @example [
       *       10,
       *       30,
       *       50,
       *       70,
       *       90
       *     ]
       */
      exceedenceProbabilities?: number[];
    };
    /** @description Contains function reference data. */
    FunctionDTO: {
      /**
       * @description The function code
       * @example C
       */
      code?: string;
      /**
       * @description The abbreviation
       * @example OBS
       */
      abbreviation?: string;
      /**
       * @description The name
       * @example current observation
       */
      name?: string;
    };
    /** @description Contains instrument reference data. */
    InstrumentDTO: {
      /**
       * @description The instrument name
       * @example 150" transducer - unknown
       */
      name?: string;
      /**
       * Format: int32
       * @description The transducer length
       * @example 150
       */
      transducerLength?: number;
      /**
       * Format: int32
       * @description The data precision adjustment
       * @example 0
       */
      dataPrecisionAdjustment?: number;
      /**
       * @description The manufacturer
       * @example Sensotec/Druck/Edcliff
       */
      manufacturer?: string;
      /**
       * @description The model
       * @example unknown
       */
      model?: string;
      /**
       * @description Is this instrument active
       * @example false
       */
      active?: boolean;
    };
    /** @description Contains network reference data. */
    NetworkDTO: {
      /**
       * @description The network code
       * @example USGS
       */
      code?: string;
      /**
       * @description The network name
       * @example STREAMFLOW
       */
      name?: string;
      /**
       * @description The network description
       * @example STREAMFLOW NETWORK STATIONS
       */
      description?: string;
    };
    /** @description Contains physical element reference data. */
    PhysicalElementDTO: {
      /**
       * @description The physical element name
       * @example snow depth
       */
      name?: string;
      /**
       * @description The SHEF physical element code
       * @example SD
       */
      shefPhysicalElementCode?: string;
    };
    /** @description Contains one or more types of reference data. */
    ReferenceDataDTO: {
      /** @description Contains DCO reference data. */
      dcos?: components['schemas']['DcoDTO'][];
      /** @description Contains duration reference data. */
      durations?: components['schemas']['DurationDTO'][];
      /** @description Contains element reference data. */
      elements?: components['schemas']['ElementDTO'][];
      /** @description Contains forecast period reference data. */
      forecastPeriods?: components['schemas']['ForecastPeriodDTO'][];
      /** @description Contains function reference data. */
      functions?: components['schemas']['FunctionDTO'][];
      /** @description Contains instrument reference data. */
      instruments?: components['schemas']['InstrumentDTO'][];
      /** @description Contains network reference data. */
      networks?: components['schemas']['NetworkDTO'][];
      /** @description Contains physical element reference data. */
      physicalElements?: components['schemas']['PhysicalElementDTO'][];
      /** @description Contains State reference data. */
      states?: components['schemas']['StateDTO'][];
      /** @description Contains unit reference data. */
      units?: components['schemas']['UnitDTO'][];
    };
    /** @description Contains reservoir metadata */
    ReservoirMetadataDTO: {
      /**
       * @description The capacity of the reservoir in acre-feet
       * @example 153000
       */
      capacity?: number;
      /**
       * @description The elevation of the reservoir (in feet) when it is at capacity
       * @example 350
       */
      elevationAtCapacity?: number;
      /**
       * @description The usable capacity of the reservoir in acre-feet
       * @example 148640
       */
      usableCapacity?: number;
    };
    /** @description Contains state reference data. */
    StateDTO: {
      /**
       * @description The state code
       * @example CO
       */
      code?: string;
      /**
       * @description The state FIPS number code
       * @example 08
       */
      fipsNumber?: string;
      /**
       * @description The state name
       * @example COLORADO
       */
      name?: string;
      /**
       * @description The country code
       * @example US
       */
      countryCode?: string;
    };
    /** @description Contains metadata about a station */
    StationDTO: {
      /**
       * @description The station triplet of the station
       * @example 302:OR:SNTL
       */
      stationTriplet?: string;
      /**
       * @description The id of the station
       * @example 302
       */
      stationId: string;
      /**
       * @description The 2-character state code of the station
       * @example OR
       */
      stateCode?: string;
      /**
       * @description The network code of the station
       * @example SNTL
       */
      networkCode?: string;
      /**
       * @description The name of the station
       * @example ANEROID LAKE #2
       */
      name?: string;
      /**
       * @description The DCO code of the station
       * @example OR
       */
      dcoCode?: string;
      /**
       * @description The name of the county that the station is located in
       * @example Wallowa
       */
      countyName?: string;
      /**
       * @description The hydrologic unit code of the station
       * @example 170601050101
       */
      huc?: string;
      /**
       * @description The elevation (in feet) of the station
       * @example 7400
       */
      elevation?: number;
      /**
       * @description The latitude of the station
       * @example 45.21328
       */
      latitude?: number;
      /**
       * @description The longitude of the station
       * @example 45.21328
       */
      longitude?: number;
      /**
       * @description The timezone offset from GMT of the data for the station
       * @example -8
       */
      dataTimeZone?: number;
      /** @description The NRCS pedon code for the station */
      pedonCode?: string;
      /**
       * @description The SHEF id of the station
       * @example ANR03
       */
      shefId?: string;
      /**
       * @description The entity in charge of the station
       * @example NRCS
       */
      operator?: string;
      /**
       * @description The date that the station was put into service
       * @example 1980-10-01 00:00
       */
      beginDate?: string;
      /**
       * @description The date that the station was taken out of service or 2100-01-01 if still in service
       * @example 2100-01-01
       */
      endDate?: string;
      forecastPoint?: components['schemas']['ForecastPointDTO'];
      reservoirMetadata?: components['schemas']['ReservoirMetadataDTO'];
      /** @description The station elements of the station */
      stationElements?: components['schemas']['StationElementDTO'][];
      /**
       * @description Hydrologic units within 5000m of this station
       * @example [
       *       "170501041601",
       *       "170501070301",
       *       "170501070404",
       *       "170501041603",
       *       "170501041703",
       *       "170501041304"
       *     ]
       */
      associatedHucs?: string[];
    };
    /** @description Contains data for a station and one or more station elements */
    StationDataDTO: {
      /**
       * @description The station triplet of the station
       * @example 302:OR:SNTL
       */
      stationTriplet?: string;
      data?: components['schemas']['DataDTO'][];
    };
    /** @description Contains information about a station element */
    StationElementDTO: {
      /**
       * @description The element code
       * @example WTEQ
       */
      elementCode?: string;
      /**
       * Format: int32
       * @description The ordinal of the station element
       * @example 1
       */
      ordinal?: number;
      /**
       * Format: int32
       * @description The height/depth of the station element in inches
       * @example null
       */
      heightDepth?: number;
      /**
       * @description The duration name of the station element
       * @example DAILY
       * @enum {string}
       */
      durationName?: 'DAILY, HOURLY, SEMIMONTHLY, MONTHLY, CALENDAR_YEAR, WATER_YEAR';
      /**
       * Format: int32
       * @description The data precision of the data for the station element
       * @example 2
       */
      dataPrecision?: number;
      /**
       * @description The units that the data is stored in
       * @example in
       */
      storedUnitCode?: string;
      /**
       * @description The units that the data was collected in
       * @example in
       */
      originalUnitCode?: string;
      /**
       * @description The date that the station element was put into service
       * @example 1980-10-30 15:53
       */
      beginDate?: string;
      /**
       * @description The date that the station element was taken out of service or 2100-01-01 if still in service
       * @example 2100-01-01
       */
      endDate?: string;
      /**
       * @description true/false if the station element data is derived
       * @example false
       */
      derivedData?: boolean;
    };
    TimingCentralTendenciesDTO: {
      /** @description Median month, day and value in which snow water equivalent peak occurs */
      medianPeak?: components['schemas']['TimingWithValueDTO'];
      /** @description Median month and day in which snow water equivalent onset occurs */
      medianOnset?: components['schemas']['TimingDTO'];
      /** @description Median month and day in which snow water equivalent meltout occurs */
      medianMeltout?: components['schemas']['TimingDTO'];
      /** @description Average month, day and value in which snow water equivalent peak occurs */
      averagePeak?: components['schemas']['TimingWithValueDTO'];
      /** @description Average month and day in which snow water equivalent onset occurs */
      averageOnset?: components['schemas']['TimingDTO'];
      /** @description Average month and day in which snow water equivalent meltout occurs */
      averageMeltout?: components['schemas']['TimingDTO'];
    };
    TimingDTO: {
      /**
       * Format: int32
       * @description The month
       */
      month?: number;
      /**
       * Format: int32
       * @description The day
       */
      day?: number;
    };
    TimingWithValueDTO: {
      /**
       * Format: int32
       * @description The month
       */
      month?: number;
      /**
       * Format: int32
       * @description The day
       */
      day?: number;
      /**
       * @description The value
       * @example 23.2
       */
      value?: number;
    };
    /** @description Contains unit reference data. */
    UnitDTO: {
      /**
       * @description The unit code
       * @example bar
       */
      code?: string;
      /**
       * @description The singular unit name
       * @example bar
       */
      singularName?: string;
      /**
       * @description The plural unit name
       * @example bars
       */
      pluralName?: string;
      /**
       * @description The unit description
       * @example barometric pressure
       */
      description?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getStations: {
    parameters: {
      query?: {
        /** @description A comma separated list of station triplets (ie. stationId:stateCode:networkCode).  Any portion of the triplet can contain the '\*' wildcard character.  For example, if you want all SNOTEL stations in OR or WA, you can request '*:OR:SNTL, *:WA:SNTL'. */
        stationTriplets?: string;
        /** @description A comma separated list of station names (can contain wildcards) */
        stationNames?: string;
        /** @description A comma separated list of DCO codes */
        dcoCodes?: string;
        /** @description A comma separated list of county names (can contain wildcards).  If specified, only stations from at least one of the counties specified will be returned. */
        countyNames?: string;
        /** @description A comma separated list of elements in the format elementCode:heightDepth:ordinal.  Any part of the element string can contain the '*' wildcard character.  The heightDepth and ordinal are optional.  If heightDepth is not specified then it is assumed to be null.  If the ordinal is not specified, then it is assumed to be 1.  The heightDepth is in inches. The list of stations will be filtered to only those that contain at least one of the elements specified and the list of stations elements will be filter to only those that have these elements.  Examples: PREC, WTEQ, SMS:\*, PREC::2 */
        elements?: string;
        /** @description A comma separated list of durations.  The available durations are: HOURLY, DAILY, SEMIMONTHLY, MONTHLY, CALENDAR_YEAR, WATER_YEAR, and SEASONAL.  Only stations that have a station element for at least one of the durations specified will be returned.  The list of station elements returned will be limited to these durations. */
        durations?: string;
        /** @description A comma separated list of hucs (can contain wildcards) */
        hucs?: string;
        /** @description If true, return forecast point metadata for stations that are forecast points */
        returnForecastPointMetadata?: boolean;
        /** @description If true, return reservoir metadata for reservoir stations */
        returnReservoirMetadata?: boolean;
        /** @description If true, return the list of station elements for each station */
        returnStationElements?: boolean;
        /** @description If true, only return active stations and station elements */
        activeOnly?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful retrieval of the station metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationDTO'][];
        };
      };
      /** @description Bad request. One or more of the parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getReferenceData: {
    parameters: {
      query?: {
        /** @description A comma-separated list of reference data to return. Options include: dcos, durations, elements, forecastPeriods, functions, instruments, networks, physicalElements, states, and units. If not specified, all the lists are returned. */
        referenceLists?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful retrieval of the data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReferenceDataDTO'][];
        };
      };
      /** @description Bad request. Invalid parameter. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getForecasts: {
    parameters: {
      query: {
        /** @description A comma separated list of station triplets (ie. stationId:stateCode:networkCode). Any portion of the triplet can contain the wildcard character. For example, if you want all USGS stations in OR or WA, you can request '*:OR:USGS, *:WA:USGS'. */
        stationTriplets: string;
        /** @description A comma separated list of element codes. Examples: RESC, SRVO, SRVOO, JDAY, REST */
        elementCodes?: string;
        /** @description The beginning of the publication date period for which to retrieve data. Expects either 'yyyy-MM-dd' or 'MM/dd/yyyy' format. Defaulted to the start of the current water year, if not specified. */
        beginPublicationDate?: string;
        /** @description The end of the publication date period for which to retrieve data. Expects either 'yyyy-MM-dd' or 'MM/dd/yyyy' format. Defaulted to current day, if not specified. */
        endPublicationDate?: string;
        /** @description A comma separated list of exceedence probabilities. Example: "10,30,50" */
        exceedenceProbabilities?: string;
        /** @description A comma separated list of forecast periods. Examples: 03-01,07-31 or [03-01,07-31] or [,07-31] or [03-01,] */
        forecastPeriods?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful retrieval of the data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForecastDTO'][];
        };
      };
      /** @description Bad request. One or more of the parameters are invalid or too much data requested. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request too large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getData: {
    parameters: {
      query: {
        /** @description A comma separated list of station triplets (ie. stationId:stateCode:networkCode).  Any portion of the triplet can contain the '\*' wildcard character.  For example, if you want all SNOTEL stations in OR or WA, you can request '*:OR:SNTL, *:WA:SNTL'. */
        stationTriplets: string;
        /** @description A comma separated list of elements in the format elementCode:heightDepth:ordinal.  Any part of the element string can contain the '*' wildcard character.  The heightDepth and ordinal are optional.  If heightDepth is not specified then it is assumed to be null.  If the ordinal is not specified, then it is assumed to be 1.  The heightDepth is in inches. Examples: PREC, WTEQ, SMS:\*, PREC::2 */
        elements: string;
        /** @description The duration of the data to retrieve */
        duration?:
          | 'DAILY'
          | 'HOURLY'
          | 'SEMIMONTHLY'
          | 'MONTHLY'
          | 'CALENDAR_YEAR'
          | 'WATER_YEAR';
        /** @description The begin date of the data to retrieve. Expects either a date or a relative date. The date must be in the 'yyyy-MM-dd HH:mm' or 'MM/dd/yyyy HH:mm' format (time defaults to midnight when not specified). Relative dates can be 0 (the current date) or -n where the unit of n corresponds to the duration. */
        beginDate?: string;
        /** @description The end date of the data to retrieve. Expects either a date or a relative date. The date must be in the 'yyyy-MM-dd HH:mm' or 'MM/dd/yyyy HH:mm' format (time defaults to midnight when not specified). Relative dates can be 0 (the current date) or -n where the unit of n corresponds to the duration. */
        endDate?: string;
        /** @description The date from which to retrieve new or changed data. Expects either yyyy-MM-dd HH:mm or MM/dd/yyyy HH:mm format. Hours and minutes are optional and will be considered as 00 if not specified. */
        insertOrUpdateBeginDate?: string;
        /** @description Indicates whether data shall be returned with a timestamp at the START of the period for which it was recorded or the END */
        periodRef?: 'START' | 'END';
        /** @description The central tendencies to return with each data value.  If set to ALL, then both average and median will be returned.  If MEDIAN, only medians will be returned.  If AVERAGE, only averages will be returned. */
        centralTendencyType?: 'NONE' | 'ALL' | 'MEDIAN' | 'AVERAGE';
        /** @description If true, return the flags with each data value */
        returnFlags?: boolean;
        /** @description If true, return original values (and original flags if returnFlags=true) */
        returnOriginalValues?: boolean;
        /** @description If true, data marked as suspect will not be filtered out */
        returnSuspectData?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful retrieval of the data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationDataDTO'][];
        };
      };
      /** @description Bad request. One or more of the parameters are invalid or too much data requested. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request too large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
